### ISSUE TITLE
Querying MongoDB with predicate fails on Spark 1.4+ 

### ISSUE THREAD

**Issue by threeseed** [spirom/spark-mongodb-connector#18]
For some reason on Spark 1.4 / Spark 1.5 when doing a query against MongoDB such as:

`SELECT * FROM table WHERE column = "SomeValue"`

Fails as SomeValue is being passed through as a UTF8String as opposed to a String. This causes MongoDB driver to fail as it is unable to encode UTF8String.

The problem has been tracked down to the QueryGenerator.convertFilter method.

**Comment by threeseed** [comment]
Workaround. Change QueryGenerator to this:

``` scala
private def convertFilter(mongoFilter: Filter) : Option[(String, Any)] = {
    mongoFilter match {
      case EqualTo(attr, v) => Some(attr, convertUTF8(v))
      case GreaterThan(attr, v) => Some(attr, MongoDBObject("$gt" -> convertUTF8(v)))
      case LessThan(attr, v) => Some(attr, MongoDBObject("$lt" -> convertUTF8(v)))
      case GreaterThanOrEqual(attr, v) => Some(attr, MongoDBObject("$gte" -> convertUTF8(v)))
      case LessThanOrEqual(attr, v) => Some(attr, MongoDBObject("$lte" -> convertUTF8(v)))
      case In(attr, vs) => Some(attr, MongoDBObject("$in" -> vs.map(convertUTF8(_))))
      case _ => None
    }
  }

  private def convertUTF8(value: Any) : Any = {
    if (value.isInstanceOf[UTF8String]) value.toString else value
  }
```

**Comment by spirom** [comment]
Thanks! I'll see if I can get it rebuilt and retested with 1.4.0 in the next week or so, and do a release.

**Comment by spirom** [comment]
I applied the above fix out of expediancy although I'm still not sure it's the right approach.
